server {
    listen 80;
    server_name _;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    # GraphQL endpoint – normálně poběží přes index.php stejně, ale můžeš to mít explicitně
    location /graphql {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_buffer_size 16k;
        fastcgi_buffers 4 16k;
    }

    location ~* \.(jpg|jpeg|png|gif|css|js|ico|svg)$ {
        try_files $uri $uri/ @php;
        expires 1M;
        access_log off;
    }

    location @php {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root/index.php;
        include fastcgi_params;
    }

    client_max_body_size 10M;
}
